# PyTorch入門
Deep Learning Frameworkの一つであるPyTorchについて解説し、自分がイメージしたNeural Networkを設計できるようになることが目的である。基本的には公式ページのチュートリアルを自分で進めていけばPyTorchを理解することができる( https://pytorch.org/ )。

## Deep Learning Frameworkとは
Deep Learning FrameworkとはNeural Networkを記述するために利用されるライブラリの集合のことである。初期のDeep Learning Frameworkでは自動微分を提供することが主であり、自動微分を用いることで誤差逆伝播による学習が容易となる。

有名なDeep Learning Frameworkとしては、以下のものが挙げられる。
1. TensorFlow: Googleから提供され、define and runで実装されている。おそらく世界でもっとも利用されているDeep Learning Framework。TensorFlow2.0では、define by runで実装されることがアナウンスされている。TensorFlow自体を直接利用する人は少なく、Kerasをフロントエンドとして利用することが多い。TensorFlow2.0ではKerasが組み込まれることがアナウンスされている。
2. PyTorch: エンジニアのコミュニティをベースに開発され、define by runで実装されている。もともとChainerよりforkされ、LuaのTorchのアイデアが組み合わされている。アカデミックな世界でよく利用されている。
3. Caffe、Caffe2: UCBのYangqing Jia(現Facebook)が開発し、define and runで実装されている。特に画像認識の分野でよく使われている。
4. MXNet: ワシントン大学とカーネギーメロン大学で開発され、スケーラビリティに優れたDeep Learning Frameworkです。多くの言語(Python、R、C++など)から利用できる。
5. CNTK: Microsoftが開発している。

世界的にはTensorFlowとPyTorchが2大Deep Learning Frameworkとなる。

## Define and runとDefine by runとは
Define and runでは、まずNeural Networkの構造を定義したのち、入力データを処理していく。このため、データを処理する前にNeural Networkの構造が定義済みになっている必要があるため、事前にNeural Networkの構造の最適化などの処理が可能である。一方、時系列データやテキストデータを扱う場合、入力データの長さが変化するため、柔軟に対応できない傾向がある。

一方、Define by runでは、事前にNeural Networkの構造を定義せず、入力データの処理手順を記載するのと同時に動的にNeural Networkを構築する手法である。例えば、if文などを利用した場合はNeural Networkの構造が変化することが容易に想像できるが、define by runでは柔軟に対応ができる。Define and runではif文で使い分けられる複数のNeural Networkを事前に作成し、個別に学習する必要がある。しかし、実行時までNeural Networkの構造が決定しないため、最適化などについては不利になる場合がある。

## Colaboratoryの環境を確認する
研究のプログラムなどをColaboratory上で実行した場合、プログラムの実行環境について明確にする必要がある。このため、Colaboratoryの動作環境の調べ方を紹介する。

### CPUのバージョンを確認する

In [ ]:
!cat /proc/cpuinfo
!nvidia-smi

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	:

### メモリの情報を確認する

In [ ]:
!cat /proc/meminfo

MemTotal:       13302924 kB
MemFree:        10270540 kB
MemAvailable:   12416964 kB
Buffers:          133128 kB
Cached:          2142804 kB
SwapCached:            0 kB
Active:          1069584 kB
Inactive:        1668108 kB
Active(anon):     421488 kB
Inactive(anon):      448 kB
Active(file):     648096 kB
Inactive(file):  1667660 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               284 kB
Writeback:             0 kB
AnonPages:        461788 kB
Mapped:           256532 kB
Shmem:              1192 kB
KReclaimable:     144284 kB
Slab:             194272 kB
SReclaimable:     144284 kB
SUnreclaim:        49988 kB
KernelStack:        5040 kB
PageTables:         6132 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6651460 kB
Committed_AS:    3156724 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       45044 kB
VmallocChunk:          0 kB
Percpu:          

### Pythonのバージョンを確認する

In [ ]:
import sys

print(sys.version)

3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]


## PyTorchの利用
Google ColaboratoryではあらかじめPyTorchがインストールされているので、何も設定しない状況で利用が可能である。もし、GPUを使いたい場合は、メニューの「ランタイム」-「ラインタイムのタイプを変更」の「ハードウェア アクセラレータ」で「GPU」を選択すればよい
]

### PyTorchのバージョンを確認する

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.__version__)

True
1.9.0+cu111


### (参考)TensorFlowのバージョンを確認する

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


### 定数を作成する
基本的にPyTorchで利用するデータ型はテンソル(多次元配列)です。基本的にはtorch.tensor()を使って生成します。値には型があるので、指定したい場合はdtypeでtorch.intやtorch.floatなどを指定すればよい。関数によっては値の型が限定されている場合があるので、リファレンスなどを参考に指定するようにしてください。

In [ ]:
import torch

# 整数を定義する
x1 = torch.tensor([5])
print(x1)

# 小数を定義する
x2 = torch.tensor([1.5])
print(x2)

# 2x2行列を定義する
mat1 = torch.tensor([[1, 2], [3, 4]])
print(mat1)

# 2x2の全要素が1の行列
mat2 = torch.ones(2, 2)
print(mat2)

# 2X2のゼロ行列
mat3 = torch.zeros(2, 2)
print(mat3)

# 2x2の単位行列
mat4 = torch.eye(2)
print(mat4)

# 2x2の単位行列の要素をtorch.float型に指定
mat4 = torch.eye(2, dtype=torch.float)

tensor([5])
tensor([1.5000])
tensor([[1, 2],
        [3, 4]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 0.],
        [0., 1.]])


### 行列の演算を行う
基本的にはNumpyと同じ演算が用意されている。

In [ ]:
# 積などの演算を行うには、dtype=np.float32にしておくこと
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
matrix2 = torch.tensor([[5., 6.], [7., 8.]])

# 行列の転置
print(matrix1.T)

# 行列の和
print(matrix1 + matrix2)

# 行列の項別積
print(matrix1 * matrix2)

# 行列積
print(torch.matmul(matrix1, matrix2))

# 逆行列
print(torch.inverse(matrix1))

tensor([[1., 3.],
        [2., 4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[19., 22.],
        [43., 50.]])
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


### その他の便利な操作


In [ ]:
import numpy as np

# データのサイズを調べる
print(matrix1.size())

# 行列の形を変える
# 2x2 -> 1x4
tmp1 = matrix1.reshape(1, 4)
print(tmp1)
print(tmp1.shape)

# 2x2 -> 4
tmp2 = matrix1.reshape(4)
print(tmp2)
print(tmp2.shape)

# 2x2 -> 1x2x2
tmp3 = matrix1.reshape(1, 2, 2)
print(tmp3)
print(tmp3.shape)

# 2x2 -> 1x1x4
tmp4 = matrix1.reshape(1, 1, -1)
print(tmp4)
print(tmp4.shape)

# Numpyとして値を表示
# 計算履歴がついている場合は必ずdetach()が必要
print(tmp4.detach().numpy())

# Numpyからtensorを作成
print(torch.from_numpy(np.array([[1, 2], [3, 4]])))

torch.Size([2, 2])
tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
tensor([1., 2., 3., 4.])
torch.Size([4])
tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([1, 2, 2])
tensor([[[1., 2., 3., 4.]]])
torch.Size([1, 1, 4])
[[[1. 2. 3. 4.]]]
tensor([[1, 2],
        [3, 4]])


### 式を書く
#### 式の定義
次のような式をPyTorch上で定義してみる
$$ y = 2 x + 1 $$
これだけだとNumpyと大きく異ならないが、PyTorchでは微分を自動的に計算することができる。具体的には、xが変数であり、微分を持つことを明確にするために、定義するときにrequires_gradをTrueに設定する。また、y.backward()により出力から微分を計算する。

In [ ]:
x = torch.tensor([1.], requires_grad=True)

# 式の定義と計算
y = 2 * x + 1
print(y)

y.backward()
print(x.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([2.])


### パーセプトロンを定義する
パーセプトロンはシンプルなモデルであり、入力と結合荷重による重み付き和で表されるものである。PyTorchでは簡単にこのようなモデルを定義することができる。結合荷重はtorch.nnで提供されているものを用いればよい。単純なパーセプトロンで用いられる全結合層はtorch.nn.Linear()を利用して定義すれば良い。torch.nn.Linear()の引数は、入力データの次元と出力データの次元を引数として呼び出すこととなる。初期値は乱数により設定されている。

In [ ]:
import torch.nn as nn

# ニューロン間の結合荷重を定義
# 重みは乱数により設定
w = nn.Linear(1, 1)
print(w.weight)
print(w.bias)

x = torch.tensor([[0.]], requires_grad=True)
y = w(x)
print(y)

y.backward()
print(x.grad)

Parameter containing:
tensor([[0.0484]], requires_grad=True)
Parameter containing:
tensor([-0.3335], requires_grad=True)
tensor([[-0.3335]], grad_fn=<AddmmBackward>)
tensor([[0.0484]])


### 3層ニューラルネットワークを定義する
3層ニューラルネットワークをパーセプトロンの定義を参考に定義してみよう。3層ニューラルネットワークは全結合層が2層重なっているので、パーセプトロンを2つ積み重ねた形となる。また隠れ層の出力には一般的に非線形な活性化関数を適用する。活性関数などの関数はtorchで定義されており、今はtorch.sigmoid()を利用する。

In [ ]:
# 3層ニューラルネットワークの結合荷重を定義する。
w1 = nn.Linear(2, 2)
w2 = nn.Linear(2, 2)

# 3層ニューラルネットワークでの処理を記述する。
# 活性化関数にはシグモイド関数を用いる。
x = torch.tensor([[1., 1.]])
h = torch.sigmoid(w1(x))
o = torch.sigmoid(w2(h))
print(o)

tensor([[0.3669, 0.6009]], grad_fn=<SigmoidBackward>)


### クラスを用いて多層ニューラルネットワークを定義する
ニューラルネットワークの定義の方法としてクラスを用いる方法がある。クラスを用いてニューラルネットワークを定義することで、ニューラルネットワークを定義する部分とデータを処理する部分に分けることができ、理解しやすいプログラムを作成することができる。

クラスとしてプログラムを定義するための一つの方法として、torch.nn.Moduleを用いる方法を説明する。以下に3層ニューラルネットワークの定義を示す。ここでは、入力層、隠れ層、出力層は全て2とする。

In [ ]:
class MLP(nn.Module): #クラスの名前を定義する。このとき、引数にnn.Moduleをつけること
  def __init__(self, input_size, hidden_size, output_size): #クラスを作成するときの初期設定を行う。引数はselfを先頭に後に必要なものを追加
    super(MLP, self).__init__() #必ず必要。最初の引数に自分が定義したクラス名を記述。これにより、上位クラスを継承

    self.l1 = nn.Linear(input_size, hidden_size) # 各層の入力と出力の次元を指定。省略不可
    self.l2 = nn.Linear(hidden_size, output_size)

  def forward(self, x): # オブジェクトから呼び出されたときに実行される関数
    h = torch.sigmoid(self.l1(x))
    o = torch.sigmoid(self.l2(h))
    return o

model = MLP(2, 2, 2)
x = torch.tensor([[1., 1.]])
print(model(x))

tensor([[0.2958, 0.6314]], grad_fn=<SigmoidBackward>)


### 練習問題
上記のプログラムを参考にして、入力層のサイズが2、隠れ層のサイズが3、出力層のサイズが2となる3層ニューラルネットワークを定義して、適当な値の入力に対する出力を求めなさい。

In [1]:
import torch
import torch.nn as nn
class MLP2(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP2, self).__init__()

        self.l1 = nn.Linear(input_size, hidden_size)
        self.l2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        h = torch.sigmoid(self.l1(x))    
        o = torch.sigmoid(self.l2(h))
        return o

model = MLP2(2, 3, 2)
x = torch.tensor([[1., 1.]])
print(model(x))        

tensor([[0.5031, 0.4605]], grad_fn=<SigmoidBackward>)


### ニューラルネットワークを学習する
PyTorchなどのDeep Learning Frameworkでは、ニューラルネットワークの学習が簡単に行える。ニューラルネットワークの学習は誤差逆伝播法で行われ、誤差逆伝播は勾配法と等価なため、Deep Learning Frameworkが提供される微分計算が重要となる。

勾配法に関しては、基本的なものである確率的最急降下法(SGD)、ADAMなどの手法が実装されている。ここでは、具体的なアルゴリズムについての説明は割愛して、使用方法について紹介する。

ここでは、$$ y = 2\sqrt{x_1^2 + x_2^2} + \epsilon $$を3層ニューラルネットワークでシミュレートすることを考える。トレーニングデータとしては、それぞれ[-10, 10]の間に0.1区切りでの値を用いる。

In [ ]:
class MLP(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(MLP, self).__init__()

    self.l1 = nn.Linear(input_size, hidden_size)
    self.l2 = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    h = torch.sigmoid(self.l1(x))
    o = self.l2(h)
    return o

x = []
for i in range(-100, 101):
  for j in range(-100, 101):
    x.append([i/10, j/10])
x = torch.tensor(x)
y = 2 * torch.sqrt(torch.diag(torch.matmul(x, x.T)).reshape(-1, 1)) + (torch.rand(x.size()[0], 1) - 0.5) * 0.01

model = MLP(2, 3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1.0e-2)
criterion = nn.MSELoss()

for i in range(10000):
  pred = model(x)
  error = criterion(pred, y)
  print(i+1, error.item())
  optimizer.zero_grad()
  error.backward()
  optimizer.step()

1 291.6379699707031
2 273.6947021484375
3 257.0739440917969
4 241.59124755859375
5 227.10057067871094
6 213.479736328125
7 200.61595153808594
8 188.3868865966797
9 176.64181518554688
10 165.27304077148438
11 154.59011840820312
12 144.81771850585938
13 135.6643829345703
14 127.08856201171875
15 119.06526947021484
16 111.5635986328125
17 104.54153442382812
18 97.94039916992188
19 91.68592071533203
20 85.74258422851562
21 80.24989318847656
22 75.33966064453125
23 70.90695190429688
24 66.88573455810547
25 63.24771499633789
26 59.966461181640625
27 57.015228271484375
28 54.36749267578125
29 51.997337341308594
30 49.87986373901367
31 47.99142837524414
32 46.309776306152344
33 44.8142204284668
34 43.48563003540039
35 42.306453704833984
36 41.26067352294922
37 40.333736419677734
38 39.51249694824219
39 38.78511428833008
40 38.14094161987305
41 37.570457458496094
42 37.06515884399414
43 36.61745834350586
44 36.220603942871094
45 35.86860275268555
46 35.556129455566406
47 35.27847671508789
48 35

KeyboardInterrupt: ignored

入出力データの形式をチェック  
先頭から 3 このデータをスライスで切り取って表示している．

In [ ]:
print(x[0:3])
print(y[0:3])

tensor([[-10.0000, -10.0000],
        [-10.0000,  -9.9000],
        [-10.0000,  -9.8000]])
tensor([[28.2872],
        [28.1432],
        [28.0024]])


2 入力 1 出力がそれぞれベクトルになっていて，それらがまとまってデータ数と同じ大きさの次元のテンソルになっている．

ここでは、予測値と正解とのズレを平均二乗誤差(torch.nn.MSELoss())で評価し、確率的勾配降下法(toch.optim.SGD())を用いて修正している。つまり、平均二乗誤差が0になるようにニューラルネットワークを修正することとなる。

このため、表示されている値が少しずつ減少しているので、学習が進んでいることを表しているとみなせ、学習の進捗状況を判断する指標として利用することができる。ただし、この訓練データでは出力は1より大きくなる範囲を含んでいるが、ニューラルネットワークの出力は0〜1に制限されている。このため、最終的には誤差が残ってしまい、このプログラムでは誤差が0になることはない。

### 練習問題
XOR問題を解く3層ニューラルネットワークを作成し、学習しなさい。
XOR問題とは以下のような入出力を持つ関数を近似する問題である。

|X1|X2|Y|
|:-----|:-----|:------|
|0|0|0|
|0|1|1|
|1|0|1|
|1|1|0|


- ヒント
  - 今回の問題にも前述の model クラスは使用できる．
  - 入力 2 ビットで考えると XOR の入力は上記の通り (0,0), (0,1), (1,0), (1,1)
  - 出力は 1 ビットで 0 か 1 となる．
  - PyTorch の tensor での入出力のデータの表現と上記のプログラムの内容を考えると，2 入力 (2 次元) のベクトルが 4 個入っているテンソルと 1 出力 (1 次元) のベクトルが 4 個入っているテンソルがそれぞれ入力と正解になりそう．


In [2]:
import torch.nn as nn 
import torch

class MLP(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(MLP, self).__init__()

    self.l1 = nn.Linear(input_size, hidden_size)
    self.l2 = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    h = torch.sigmoid(self.l1(x))
    o = self.l2(h)
    return o

x = []
for i in range(2):
    for j in range(2):
        x.append([i, j])
x = torch.tensor(x, dtype=torch.float)
y = torch.tensor([[0.], [1.], [1.], [0.]]) 
print(x)
print(y)

model = MLP(2, 3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1.0e-1)
criterion = nn.MSELoss()

for i in range(10000):
  pred = model(x)
  error = criterion(pred, y)
  print(i+1, error.item())
  optimizer.zero_grad()
  error.backward()
  optimizer.step()

print(pred)  

ストリーミング出力は最後の 5000 行に切り捨てられました。
5005 3.9256597972325835e-11
5006 3.9256597972325835e-11
5007 3.9256597972325835e-11
5008 3.9256597972325835e-11
5009 3.9256597972325835e-11
5010 3.9256597972325835e-11
5011 3.9256597972325835e-11
5012 3.9256597972325835e-11
5013 3.9256597972325835e-11
5014 3.9256597972325835e-11
5015 3.9256597972325835e-11
5016 3.9256597972325835e-11
5017 3.9256597972325835e-11
5018 3.9256597972325835e-11
5019 3.9256597972325835e-11
5020 3.9256597972325835e-11
5021 3.9256597972325835e-11
5022 3.9256597972325835e-11
5023 3.9256597972325835e-11
5024 3.9256597972325835e-11
5025 3.9256597972325835e-11
5026 3.9256597972325835e-11
5027 3.9256597972325835e-11
5028 3.9256597972325835e-11
5029 3.9256597972325835e-11
5030 3.9256597972325835e-11
5031 3.9256597972325835e-11
5032 3.9256597972325835e-11
5033 3.9256597972325835e-11
5034 3.9256597972325835e-11
5035 3.9256597972325835e-11
5036 3.9256597972325835e-11
5037 3.9256597972325835e-11
5038 3.9256597972325835e-11
5039 3.925659797

In [3]:
#モデルが正しく学習されているかの確認

x_test = torch.tensor([0., 0.])
answer = model(x_test)
print(answer)

x_test = torch.tensor([0., 1.])
answer = model(x_test)
print(answer)

x_test = torch.tensor([1., 0.])
answer = model(x_test)
print(answer)

x_test = torch.tensor([1., 1.])
answer = model(x_test)
print(answer)

tensor([5.6624e-06], grad_fn=<AddBackward0>)
tensor([1.0000], grad_fn=<AddBackward0>)
tensor([1.0000], grad_fn=<AddBackward0>)
tensor([6.7353e-06], grad_fn=<AddBackward0>)
